name    'puppet-iphawk'
version '0.0.1'
source 'https://github.com/openstack-hyper-v/puppet-iphawk'
author 'Peter J. Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'A Puppet module for configuring IPHawk'
description 'A Puppet module for configuring IPHawk'
project_page 'https://github.com/openstack-hyper-v/puppet-iphawk'
dependency 'jfryman/nginx', '>= 0.0.7'
dependency 'puppetLabs/mysql', '>= 1.0.0'
